version: '0.8.0-{build}'

image: Visual Studio 2017

platform:
  - x64

clone_folder: c:\projects\nova-renderer
clone_depth: 1
skip_tags: true

environment:
  VULKAN_SDK: C:\VulkanSDK\1.1.97.0

init:
  - cmd: cmake --version
  - cmd: msbuild /version
 
configuration:
  - Debug

install:
  - cmd: git submodule update --init --recursive
  - cmd: curl --silent --show-error --output VulkanSDK.exe https://cwfitz.com/s/19028-082433-VulkanSDK-1.1.97.0-Installer.exe
  - cmd: .\VulkanSDK.exe /S

before_build:
  - cmd: cd C:\projects\nova-renderer
  - cmd: md build
  - cmd: cd build
  - cmd: cmake .. -G "Visual Studio 15 2017 Win64" -DNOVA_TEST=On "-DCMAKE_C_FLAGS=/D_CRT_SECURE_NO_WARNINGS=1" "-DCMAKE_CXX_FLAGS=/D_CRT_SECURE_NO_WARNINGS=1"

build:
  project: C:\projects\nova-renderer\build\nova-renderer.sln

test_script:
- cmd: dir C:\projects\nova-renderer\build\%CONFIGURATION%\
- cmd: C:\projects\nova-renderer\build\%CONFIGURATION%\nova-test-unit.exe
